/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrintRouteImport } from './routes/print'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomerDisplayRouteImport } from './routes/customer-display'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashierIndexRouteImport } from './routes/cashier.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppPromotionsRouteImport } from './routes/_app.promotions'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppOutletsRouteImport } from './routes/_app.outlets'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppImportExportRouteImport } from './routes/_app.import-export'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app.suppliers.index'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app.purchase-orders.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppOutletsIndexRouteImport } from './routes/_app.outlets.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as PrintReceiptIdRouteImport } from './routes/print.receipt.$id'
import { Route as CashierShiftOpenRouteImport } from './routes/cashier.shift.open'
import { Route as CashierShiftCloseRouteImport } from './routes/cashier.shift.close'
import { Route as AppSuppliersNewRouteImport } from './routes/_app.suppliers.new'
import { Route as AppReportsShiftsRouteImport } from './routes/_app.reports.shifts'
import { Route as AppReportsSalesRouteImport } from './routes/_app.reports.sales'
import { Route as AppReportsProfitRouteImport } from './routes/_app.reports.profit'
import { Route as AppReportsProductsRouteImport } from './routes/_app.reports.products'
import { Route as AppReportsPaymentsRouteImport } from './routes/_app.reports.payments'
import { Route as AppReportsInventoryRouteImport } from './routes/_app.reports.inventory'
import { Route as AppPurchaseOrdersNewRouteImport } from './routes/_app.purchase-orders.new'
import { Route as AppPurchaseOrdersIdRouteImport } from './routes/_app.purchase-orders.$id'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppProductsIdRouteImport } from './routes/_app.products.$id'
import { Route as AppInventoryHistoryRouteImport } from './routes/_app.inventory.history'
import { Route as AppInventoryAdjustmentRouteImport } from './routes/_app.inventory.adjustment'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as AppOutletsIdTransferRouteImport } from './routes/_app.outlets.$id.transfer'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDisplayRoute = CustomerDisplayRouteImport.update({
  id: '/customer-display',
  path: '/customer-display',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierIndexRoute = CashierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashierRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOutletsRoute = AppOutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppImportExportRoute = AppImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuppliersRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchaseOrdersRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOutletsIndexRoute = AppOutletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOutletsRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const PrintReceiptIdRoute = PrintReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => PrintRoute,
} as any)
const CashierShiftOpenRoute = CashierShiftOpenRouteImport.update({
  id: '/shift/open',
  path: '/shift/open',
  getParentRoute: () => CashierRoute,
} as any)
const CashierShiftCloseRoute = CashierShiftCloseRouteImport.update({
  id: '/shift/close',
  path: '/shift/close',
  getParentRoute: () => CashierRoute,
} as any)
const AppSuppliersNewRoute = AppSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSuppliersRoute,
} as any)
const AppReportsShiftsRoute = AppReportsShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsProfitRoute = AppReportsProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsProductsRoute = AppReportsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsPaymentsRoute = AppReportsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsInventoryRoute = AppReportsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppPurchaseOrdersNewRoute = AppPurchaseOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchaseOrdersRoute,
} as any)
const AppPurchaseOrdersIdRoute = AppPurchaseOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPurchaseOrdersRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppInventoryHistoryRoute = AppInventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryAdjustmentRoute = AppInventoryAdjustmentRouteImport.update({
  id: '/adjustment',
  path: '/adjustment',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppOutletsIdTransferRoute = AppOutletsIdTransferRouteImport.update({
  id: '/$id/transfer',
  path: '/$id/transfer',
  getParentRoute: () => AppOutletsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRouteWithChildren
  '/customer-display': typeof CustomerDisplayRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/expenses': typeof AppExpensesRoute
  '/import-export': typeof AppImportExportRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/outlets': typeof AppOutletsRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/promotions': typeof AppPromotionsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRouteWithChildren
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRouteWithChildren
  '/users': typeof AppUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/cashier/': typeof CashierIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/inventory/adjustment': typeof AppInventoryAdjustmentRoute
  '/inventory/history': typeof AppInventoryHistoryRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/payments': typeof AppReportsPaymentsRoute
  '/reports/products': typeof AppReportsProductsRoute
  '/reports/profit': typeof AppReportsProfitRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/shifts': typeof AppReportsShiftsRoute
  '/suppliers/new': typeof AppSuppliersNewRoute
  '/cashier/shift/close': typeof CashierShiftCloseRoute
  '/cashier/shift/open': typeof CashierShiftOpenRoute
  '/print/receipt/$id': typeof PrintReceiptIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/outlets/': typeof AppOutletsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/outlets/$id/transfer': typeof AppOutletsIdTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/expenses': typeof AppExpensesRoute
  '/import-export': typeof AppImportExportRoute
  '/notifications': typeof AppNotificationsRoute
  '/promotions': typeof AppPromotionsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/cashier': typeof CashierIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/inventory/adjustment': typeof AppInventoryAdjustmentRoute
  '/inventory/history': typeof AppInventoryHistoryRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/payments': typeof AppReportsPaymentsRoute
  '/reports/products': typeof AppReportsProductsRoute
  '/reports/profit': typeof AppReportsProfitRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/shifts': typeof AppReportsShiftsRoute
  '/suppliers/new': typeof AppSuppliersNewRoute
  '/cashier/shift/close': typeof CashierShiftCloseRoute
  '/cashier/shift/open': typeof CashierShiftOpenRoute
  '/print/receipt/$id': typeof PrintReceiptIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/outlets': typeof AppOutletsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/outlets/$id/transfer': typeof AppOutletsIdTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/cashier': typeof CashierRouteWithChildren
  '/customer-display': typeof CustomerDisplayRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/import-export': typeof AppImportExportRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/outlets': typeof AppOutletsRouteWithChildren
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRouteWithChildren
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/cashier/': typeof CashierIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/inventory/adjustment': typeof AppInventoryAdjustmentRoute
  '/_app/inventory/history': typeof AppInventoryHistoryRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/_app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/_app/reports/inventory': typeof AppReportsInventoryRoute
  '/_app/reports/payments': typeof AppReportsPaymentsRoute
  '/_app/reports/products': typeof AppReportsProductsRoute
  '/_app/reports/profit': typeof AppReportsProfitRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
  '/_app/reports/shifts': typeof AppReportsShiftsRoute
  '/_app/suppliers/new': typeof AppSuppliersNewRoute
  '/cashier/shift/close': typeof CashierShiftCloseRoute
  '/cashier/shift/open': typeof CashierShiftOpenRoute
  '/print/receipt/$id': typeof PrintReceiptIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/outlets/': typeof AppOutletsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/outlets/$id/transfer': typeof AppOutletsIdTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashier'
    | '/customer-display'
    | '/forgot-password'
    | '/login'
    | '/print'
    | '/register'
    | '/reset-password'
    | '/audit-logs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/devices'
    | '/expenses'
    | '/import-export'
    | '/inventory'
    | '/notifications'
    | '/outlets'
    | '/products'
    | '/promotions'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/api/health'
    | '/cashier/'
    | '/customers/$id'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/reports/inventory'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/profit'
    | '/reports/sales'
    | '/reports/shifts'
    | '/suppliers/new'
    | '/cashier/shift/close'
    | '/cashier/shift/open'
    | '/print/receipt/$id'
    | '/customers/'
    | '/inventory/'
    | '/outlets/'
    | '/products/'
    | '/purchase-orders/'
    | '/suppliers/'
    | '/outlets/$id/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-display'
    | '/forgot-password'
    | '/login'
    | '/print'
    | '/register'
    | '/reset-password'
    | '/audit-logs'
    | '/categories'
    | '/dashboard'
    | '/devices'
    | '/expenses'
    | '/import-export'
    | '/notifications'
    | '/promotions'
    | '/reports'
    | '/settings'
    | '/users'
    | '/api/health'
    | '/cashier'
    | '/customers/$id'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/reports/inventory'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/profit'
    | '/reports/sales'
    | '/reports/shifts'
    | '/suppliers/new'
    | '/cashier/shift/close'
    | '/cashier/shift/open'
    | '/print/receipt/$id'
    | '/customers'
    | '/inventory'
    | '/outlets'
    | '/products'
    | '/purchase-orders'
    | '/suppliers'
    | '/outlets/$id/transfer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/cashier'
    | '/customer-display'
    | '/forgot-password'
    | '/login'
    | '/print'
    | '/register'
    | '/reset-password'
    | '/_app/audit-logs'
    | '/_app/categories'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/expenses'
    | '/_app/import-export'
    | '/_app/inventory'
    | '/_app/notifications'
    | '/_app/outlets'
    | '/_app/products'
    | '/_app/promotions'
    | '/_app/purchase-orders'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/users'
    | '/api/health'
    | '/cashier/'
    | '/_app/customers/$id'
    | '/_app/inventory/adjustment'
    | '/_app/inventory/history'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/purchase-orders/$id'
    | '/_app/purchase-orders/new'
    | '/_app/reports/inventory'
    | '/_app/reports/payments'
    | '/_app/reports/products'
    | '/_app/reports/profit'
    | '/_app/reports/sales'
    | '/_app/reports/shifts'
    | '/_app/suppliers/new'
    | '/cashier/shift/close'
    | '/cashier/shift/open'
    | '/print/receipt/$id'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/outlets/'
    | '/_app/products/'
    | '/_app/purchase-orders/'
    | '/_app/suppliers/'
    | '/_app/outlets/$id/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CashierRoute: typeof CashierRouteWithChildren
  CustomerDisplayRoute: typeof CustomerDisplayRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrintRoute: typeof PrintRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-display': {
      id: '/customer-display'
      path: '/customer-display'
      fullPath: '/customer-display'
      preLoaderRoute: typeof CustomerDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier/': {
      id: '/cashier/'
      path: '/'
      fullPath: '/cashier/'
      preLoaderRoute: typeof CashierIndexRouteImport
      parentRoute: typeof CashierRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outlets': {
      id: '/_app/outlets'
      path: '/outlets'
      fullPath: '/outlets'
      preLoaderRoute: typeof AppOutletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-export': {
      id: '/_app/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AppImportExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppSuppliersRoute
    }
    '/_app/purchase-orders/': {
      id: '/_app/purchase-orders/'
      path: '/'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppPurchaseOrdersRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/outlets/': {
      id: '/_app/outlets/'
      path: '/'
      fullPath: '/outlets/'
      preLoaderRoute: typeof AppOutletsIndexRouteImport
      parentRoute: typeof AppOutletsRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/print/receipt/$id': {
      id: '/print/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/print/receipt/$id'
      preLoaderRoute: typeof PrintReceiptIdRouteImport
      parentRoute: typeof PrintRoute
    }
    '/cashier/shift/open': {
      id: '/cashier/shift/open'
      path: '/shift/open'
      fullPath: '/cashier/shift/open'
      preLoaderRoute: typeof CashierShiftOpenRouteImport
      parentRoute: typeof CashierRoute
    }
    '/cashier/shift/close': {
      id: '/cashier/shift/close'
      path: '/shift/close'
      fullPath: '/cashier/shift/close'
      preLoaderRoute: typeof CashierShiftCloseRouteImport
      parentRoute: typeof CashierRoute
    }
    '/_app/suppliers/new': {
      id: '/_app/suppliers/new'
      path: '/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AppSuppliersNewRouteImport
      parentRoute: typeof AppSuppliersRoute
    }
    '/_app/reports/shifts': {
      id: '/_app/reports/shifts'
      path: '/shifts'
      fullPath: '/reports/shifts'
      preLoaderRoute: typeof AppReportsShiftsRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/profit': {
      id: '/_app/reports/profit'
      path: '/profit'
      fullPath: '/reports/profit'
      preLoaderRoute: typeof AppReportsProfitRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/products': {
      id: '/_app/reports/products'
      path: '/products'
      fullPath: '/reports/products'
      preLoaderRoute: typeof AppReportsProductsRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/payments': {
      id: '/_app/reports/payments'
      path: '/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof AppReportsPaymentsRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/inventory': {
      id: '/_app/reports/inventory'
      path: '/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AppReportsInventoryRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/purchase-orders/new': {
      id: '/_app/purchase-orders/new'
      path: '/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AppPurchaseOrdersNewRouteImport
      parentRoute: typeof AppPurchaseOrdersRoute
    }
    '/_app/purchase-orders/$id': {
      id: '/_app/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AppPurchaseOrdersIdRouteImport
      parentRoute: typeof AppPurchaseOrdersRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/inventory/history': {
      id: '/_app/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof AppInventoryHistoryRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/adjustment': {
      id: '/_app/inventory/adjustment'
      path: '/adjustment'
      fullPath: '/inventory/adjustment'
      preLoaderRoute: typeof AppInventoryAdjustmentRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/outlets/$id/transfer': {
      id: '/_app/outlets/$id/transfer'
      path: '/$id/transfer'
      fullPath: '/outlets/$id/transfer'
      preLoaderRoute: typeof AppOutletsIdTransferRouteImport
      parentRoute: typeof AppOutletsRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryAdjustmentRoute: typeof AppInventoryAdjustmentRoute
  AppInventoryHistoryRoute: typeof AppInventoryHistoryRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryAdjustmentRoute: AppInventoryAdjustmentRoute,
  AppInventoryHistoryRoute: AppInventoryHistoryRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppOutletsRouteChildren {
  AppOutletsIndexRoute: typeof AppOutletsIndexRoute
  AppOutletsIdTransferRoute: typeof AppOutletsIdTransferRoute
}

const AppOutletsRouteChildren: AppOutletsRouteChildren = {
  AppOutletsIndexRoute: AppOutletsIndexRoute,
  AppOutletsIdTransferRoute: AppOutletsIdTransferRoute,
}

const AppOutletsRouteWithChildren = AppOutletsRoute._addFileChildren(
  AppOutletsRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppPurchaseOrdersRouteChildren {
  AppPurchaseOrdersIdRoute: typeof AppPurchaseOrdersIdRoute
  AppPurchaseOrdersNewRoute: typeof AppPurchaseOrdersNewRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
}

const AppPurchaseOrdersRouteChildren: AppPurchaseOrdersRouteChildren = {
  AppPurchaseOrdersIdRoute: AppPurchaseOrdersIdRoute,
  AppPurchaseOrdersNewRoute: AppPurchaseOrdersNewRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
}

const AppPurchaseOrdersRouteWithChildren =
  AppPurchaseOrdersRoute._addFileChildren(AppPurchaseOrdersRouteChildren)

interface AppReportsRouteChildren {
  AppReportsInventoryRoute: typeof AppReportsInventoryRoute
  AppReportsPaymentsRoute: typeof AppReportsPaymentsRoute
  AppReportsProductsRoute: typeof AppReportsProductsRoute
  AppReportsProfitRoute: typeof AppReportsProfitRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppReportsShiftsRoute: typeof AppReportsShiftsRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsInventoryRoute: AppReportsInventoryRoute,
  AppReportsPaymentsRoute: AppReportsPaymentsRoute,
  AppReportsProductsRoute: AppReportsProductsRoute,
  AppReportsProfitRoute: AppReportsProfitRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppReportsShiftsRoute: AppReportsShiftsRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppSuppliersRouteChildren {
  AppSuppliersNewRoute: typeof AppSuppliersNewRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
}

const AppSuppliersRouteChildren: AppSuppliersRouteChildren = {
  AppSuppliersNewRoute: AppSuppliersNewRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
}

const AppSuppliersRouteWithChildren = AppSuppliersRoute._addFileChildren(
  AppSuppliersRouteChildren,
)

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppImportExportRoute: typeof AppImportExportRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOutletsRoute: typeof AppOutletsRouteWithChildren
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRouteWithChildren
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppImportExportRoute: AppImportExportRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOutletsRoute: AppOutletsRouteWithChildren,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppPromotionsRoute: AppPromotionsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRouteWithChildren,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CashierRouteChildren {
  CashierIndexRoute: typeof CashierIndexRoute
  CashierShiftCloseRoute: typeof CashierShiftCloseRoute
  CashierShiftOpenRoute: typeof CashierShiftOpenRoute
}

const CashierRouteChildren: CashierRouteChildren = {
  CashierIndexRoute: CashierIndexRoute,
  CashierShiftCloseRoute: CashierShiftCloseRoute,
  CashierShiftOpenRoute: CashierShiftOpenRoute,
}

const CashierRouteWithChildren =
  CashierRoute._addFileChildren(CashierRouteChildren)

interface PrintRouteChildren {
  PrintReceiptIdRoute: typeof PrintReceiptIdRoute
}

const PrintRouteChildren: PrintRouteChildren = {
  PrintReceiptIdRoute: PrintReceiptIdRoute,
}

const PrintRouteWithChildren = PrintRoute._addFileChildren(PrintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CashierRoute: CashierRouteWithChildren,
  CustomerDisplayRoute: CustomerDisplayRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrintRoute: PrintRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
